version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports: ["5432:5432"]
  app:
    build: .
    depends_on: ["db"]
    ports: ["8000:8000"]
